<?php
if($_GET[ph_del_n] && $_GET[ph_del_n] > 0){
    $files_where = explode('|',mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_faq WHERE id=".$_GET['id']), 0));
    $new_linn = '';
    if(count($files_where)>0){
        for ($fw=0;$fw<count($files_where);$fw++)
            if($_GET[ph_del_n]-1!=$fw)
                $new_linn .= $files_where[$fw].'|';
        if(strlen($new_linn)>0)
            $new_linn = substr($new_linn,0, strlen($new_linn)-1);
        $result = mysql_query("UPDATE ".MySQLprefix."_faq SET logo='".$new_linn."' WHERE id=".$_GET['id']);
    }
    ?>
    <script type="text/javascript">
        <!--
        $(document).ready(function(){
            document.location.href = document.location.href.split('&ph_del_n')[0];
        });
        //-->
    </script>
    <?php
}
$nodelete = array(1, 64, 56, 73);
if($_GET['del2'] == 1){
    $logo = mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_faq WHERE id=".$_GET['id']),0);
    if(strlen($logo)>0)
        unlink('../'.$logo);
    $result = mysql_query("DELETE FROM ".MySQLprefix."_faq WHERE id=".$_GET['id']);
    ?>
    <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Отзыв удален</div>
    <script type="text/javascript">
        function rem_mes(){
            $('.result-mess').fadeOut(1000, function(){
                $('.result-mess').remove();
            });
        }
        var mto = window.setTimeout('rem_mes()',2000);
    </script>
    <?php
}
if(strlen($_POST['name'])>0){
    if($_POST['st']!=1)
        $_POST['st'] = 0;
    $linnnn = '';
    for ($nf=0;$nf<count($_FILES["npic"]["tmp_name"]);$nf++){
        $ran = round(rand(1000000000, 9999999999), 0);
        $n_type = substr($_FILES["npic"]["name"][$nf], strrpos($_FILES["npic"]["name"][$nf], '.'), strlen($_FILES["npic"]["name"][$nf])-strrpos($_FILES["npic"]["name"][$nf], '.'));
        if(move_uploaded_file($_FILES["npic"]["tmp_name"][$nf], "uploads/".$ran.$n_type))
            $linnnn = "admin/uploads/".$ran.$n_type;
    }
    if($_POST['todo'] == 1){
        $files_where = mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_faq WHERE id=".$_POST['nid']),0);
        $linnnn = (strlen($linnnn)>0?$linnnn:$files_where);
        $upd_url = mysql_query("UPDATE ".MySQLprefix."_faq SET st=".$_POST['st'].", logo='".$linnnn."', city='".$_POST['city']."', text='".$_POST['editor2']."', name='".$_POST['name']."', email='".$_POST['email']."', rate='".$_POST['rate']."', title='".$_POST['title']."' WHERE id=".$_POST['nid']);
        ?>
        <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Информация обновлена</div>
        <script type="text/javascript">
            function rem_mes(){
                $('.result-mess').fadeOut(1000, function(){
                    $('.result-mess').remove();
                });
            }
            var mto = window.setTimeout('rem_mes()',2000);
        </script>
        <?php
    }else{
        $result = mysql_query("INSERT INTO ".MySQLprefix."_faq (st, name, city, text, rate, email, title, logo) VALUES (".$_POST['st'].", '".$_POST['name']."', '".$_POST['city']."', '".$_POST['editor2']."', '".$_POST['rate']."', '".$_POST['email']."', '".$_POST['title']."', '".$linnnn."')");
        $last_id = mysql_result(mysql_query("SELECT id FROM ".MySQLprefix."_faq ORDER BY id DESC LIMIT 0, 1"), 0);
        ?>
        <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Добавлена</div>
        <script type="text/javascript">
            function rem_mes(){
                $('.result-mess').fadeOut(1000, function(){
                    $('.result-mess').remove();
                });
            }
            var mto = window.setTimeout('rem_mes()',2000);
        </script>
        <?php
    }
}
if(!$_GET['add'] && !$_GET['edit']){
    echo '<ul class="ul" style="margin-left:100px">';
    $result = mysql_query("SELECT * FROM ".MySQLprefix."_faq ORDER BY id ASC");
    if ($result)
        while ($row = mysql_fetch_assoc($result)){
            echo '<li><span'.($row['st']==0?' style="color:grey"':'').'>'.$row['name'].'</span> - <a href="cms.php?go='.$_GET['go'].'&amp;edit=1&amp;id='.$row['id'].'#down" style="color: green;"><img alt="редактировать" src="img/edit.gif" width="16" style="vertical-align:-3px;" /></a> | ';
            if (!$_GET['del'])
                echo '<a href="cms.php?go='.$_GET['go'].'&del='.$row['id'].'#item'.$row['id'].'" title="Удаление" style="color:red"><img alt="Удалить" src="img/del.gif" width="16" style="vertical-align:-3px;" /></a>';
            if ($_GET['del'] == $row['id'])
                echo 'Подтверждаете удаление: <a href="cms.php?go='.$_GET['go'].'&del2=1&id='.$_GET['del'].'" style="color: red;" title="Удаление">ДА</a> - <a href="cms.php?go='.$_GET['go'].'" style="color: black;" title="Отмена">НЕТ</a>';
            echo '</li>';
        }
    echo '</ul>';
}
?>
    <a style="position:fixed;left:0;top:45%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;" href='cms.php?go=<?php echo $_GET['go']; ?>&amp;add=1'>Добавить отзыв</a>
<?php
if(isset($_GET['edit']) || isset($_GET['add'])){
    if(isset($_GET['edit'])){
        $new_r = mysql_query("SELECT * FROM ".MySQLprefix."_faq WHERE id=".$_GET['id']);
        if($new_r)
            if(mysql_num_rows($new_r)==1)
                $company = mysql_fetch_assoc($new_r);
    }
    ?>
    <hr/>
    <form action="" method="post" style="margin-top:40px" enctype="multipart/form-data" class="save-form">
        <div style="width:100%;overflow:hidden">
            <label style="display:block;width:14%;float:left;text-align:right;line-height:20px">Имя:</label>
            <div style="display:block;width:84%;float:right;text-align:left;">
                <input type="text" name="name" size="70" value='<?=$company['name']?>' style="border:1px solid #011393;border-radius:3px;padding:1px 5px" /> | <input type="checkbox" value="1" name="st" <?php if($_GET['add'] == 1 || ($company['st']==1 and $_GET['edit'] == 1)){ ?>checked="checked" <?php } ?>style="vertical-align:-2px" /> показывать на сайте
            </div>
        </div><br/><br/>
        <div style="width:100%;overflow:hidden">
            <label style="display:block;width:14%;float:left;text-align:right;line-height:20px">Email:</label>
            <div style="display:block;width:84%;float:right;text-align:left;">
                <input type="text" name="email" size="30" value='<?=$company['email']?>' style="border:1px solid #011393;border-radius:3px;padding:1px 5px" /> | Город: <input type="text" name="city" size="30" value='<?=$company['city']?>' style="border:1px solid #011393;border-radius:3px;padding:1px 5px" />
            </div>
        </div><br/><hr/><br/>
        <div style="width:100%;overflow:hidden">
            <label style="display:block;width:14%;float:left;text-align:right;line-height:20px">Изображение (размер 1:1 квадрат):</label>
            <div style="display:block;width:84%;float:right;text-align:left;">
                <?php
                if($_GET['edit'] == 1 && strlen($company['logo'])>0){
                    $files_where = explode('|', $company['logo']);
                    if(count($files_where)>0){
                        echo '<div style="width:100%;overflow:hidden;position:relative;">';
                        for ($fw=0;$fw<count($files_where);$fw++)
                            echo '<span style="display:block;width:150px;height:150px;overflow:hidden;float:left;border:1px solid grey;margin:1px;text-align:center;line-height:150px;position:relative;"><img src="../'.$files_where[$fw].'" style="border:0;max-height:100%;max-width:100%;vertical-align:middle;position:relative;" /><a href="cms.php?go='.$_GET['go'].'&edit=1&id='.$_GET['id'].'&ph_del_n='.($fw+1).'" style="display:block;width:16px;height:16px;position:absolute;right:0;top:0;background:url(img/b_drop.png);cursor:pointer;"></a></span>';
                        echo '</div>';
                    }
                }
                ?>
                <p class="piccs"></p>
                <script type="text/javascript">
                    <!--
                    function addformpht(){
                        $(".piccs").append('<input type="file" name="npic[]" /><br />');
                    }
                    //-->
                </script>
                <a onclick="addformpht();" style="color:blue;font-weight:bold;cursor:pointer;">Добавить фото (+1)</a>
            </div>
        </div><br/><hr/><br/>
        <div style="width:100%;overflow:hidden">
            <label style="display:block;width:14%;float:left;text-align:right;line-height:20px">Заголовок:</label>
            <div style="display:block;width:84%;float:right;text-align:left;">
                <textarea name="title" cols="90" rows="1" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$company['title']?></textarea>
            </div>
        </div><br/><br/>
        <div style="width:100%;overflow:hidden">
            <label style="display:block;width:14%;float:left;text-align:right;line-height:20px">Текст:</label>
            <div style="display:block;width:84%;float:right;text-align:left;">
                <textarea id="editor2" cols="80" rows="5" name="editor2"><?=$company['text']?></textarea>
                <script type="text/javascript">
                    <!--
                    var ckeditor2 = CKEDITOR.replace("editor2");
                    AjexFileManager.init({returnTo: "ckeditor", editor: ckeditor2, skin: "light"});
                    //-->
                </script>
            </div>
        </div>
        <input type="hidden" name="todo" value="<?php echo $_GET['edit']; ?>" />
        <input type="hidden" name="nid" value="<?php if($_GET['edit'] == 1){echo $_GET['id'];} ?>" />
        <input type="submit" name="update" value="Сохранить" style="position:fixed;left:0;top:50%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;" />
    </form>
<?php } ?>